=== yuchengxin/mybatis-ds-generator/core/src/main/resources/mybatis-ds-generator-config_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!--
          mybatis dynamic sql generator config dtd
        -->
        <!ELEMENT generatorPlusConfiguration (joinConfig?, customTypeConfig?)>

        <!--
          join config
        -->
        <!ELEMENT joinConfig (joinEntry*)>
        <!ATTLIST joinConfig
                targetPackage CDATA #REQUIRED
                targetProject CDATA #REQUIRED
                >

        <!--
          join entry
        -->
        <!ELEMENT joinEntry (joinTarget*)>
        <!ATTLIST joinEntry
                leftTable CDATA #REQUIRED
                >

        <!--
          join target table
        -->
        <!ELEMENT joinTarget EMPTY>
        <!ATTLIST joinTarget
                rightTable CDATA #REQUIRED
                property CDATA #REQUIRED
                leftTableColumn CDATA #REQUIRED
                rightTableColumn CDATA #REQUIRED
                joinType CDATA #REQUIRED
                >

        <!--
          custom type config
        -->
        <!ELEMENT customTypeConfig (customType*)>

        <!--
          custom type
        -->
        <!ELEMENT customType (genericType*)>
        <!ATTLIST customType
                columnName CDATA #REQUIRED
                javaType CDATA #REQUIRED
                property CDATA #IMPLIED
                jdbcType CDATA #IMPLIED
                typeHandler CDATA #IMPLIED
                delimitedColumnName CDATA #IMPLIED
                >

        <!--
            generic type
        -->
        <!ELEMENT genericType EMPTY>
        <!ATTLIST genericType
                javaType CDATA #REQUIRED
                >

=== yuchengxin/mybatis-ds-generator/example/src/main/resources/generator/ds-generator-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorPlusConfiguration
        PUBLIC "-//mybatis.org//DTD MyBatis Generator plus Configuration //EN"
        "https://document-1303021898.cos.ap-shanghai.myqcloud.com/mybatis-ds-generator-config_1_0.dtd">
<generatorPlusConfiguration>
    <joinConfig targetPackage="com.catyee.mybatis.example.mapper" targetProject="src/main/resources">
        <joinEntry leftTable="exam_class_grade">
            <joinTarget rightTable="exam_student" property="students" leftTableColumn="id" rightTableColumn="grade_id" joinType="MORE"/>
            <joinTarget rightTable="exam_teacher" property="regulator" leftTableColumn="regulator_id" rightTableColumn="id" joinType="ONE"/>
        </joinEntry>
    </joinConfig>

    <customTypeConfig>
        <customType columnName="grade_type" javaType="com.catyee.mybatis.example.custom.entity.GradeType"/>
        <customType columnName="gender" javaType="com.catyee.mybatis.example.custom.entity.Gender"/>
        <customType columnName="exam_type" javaType="com.catyee.mybatis.example.custom.entity.ExamType"/>

        <customType columnName="hobbies" javaType="java.util.List" typeHandler="com.catyee.mybatis.example.custom.handler.HobbyListHandler">
            <genericType javaType="com.catyee.mybatis.example.custom.entity.Hobby"/>
        </customType>
        <customType columnName="tech_courses" javaType="java.util.List" typeHandler="com.catyee.mybatis.example.custom.handler.StringListHandler">
            <genericType javaType="String"/>
        </customType>
        <customType columnName="take_courses" javaType="java.util.List" typeHandler="com.catyee.mybatis.example.custom.handler.StringListHandler">
            <genericType javaType="String"/>
        </customType>
        <customType columnName="score" javaType="java.util.Map" typeHandler="com.catyee.mybatis.example.custom.handler.ScoreMapHandler">
            <genericType javaType="String"/>
            <genericType javaType="Integer"/>
        </customType>
    </customTypeConfig>
</generatorPlusConfiguration>
